server.port=8080
server.servlet.context-path=

# 日志
logging.level.root=info
logging.file.name=/opt/devops/spring-boot-demo/logs/log.txt
#logging.level.org.springframework=warn


# 自定义配置项使用 `@ConfigurationProperties(prefix = "xxx")` 直接注入到实体类属性
# sys.id 默认为 UUID
#sys.id=spring-boot-demo-01
sys.name=spring-boot-demo
sys.ver=v1.0

# 自定义配置项使用 `@Value("${property.key:defaultValue}")` 注入
sys.author=AndyKuo
