server.port=8080
server.servlet.context-path=

# 日志
logging.level.root=info
logging.file.name=/opt/devops/spring-boot-demo/logs/log.txt
#logging.level.org.springframework=warn


# springboot-actuate 配置，生产环境请防止信息泄露和安全风险。
management.endpoints.enabled-by-default=true
management.endpoints.web.base-path=/monitor
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# 通过接口 `shutdown` 服务，慎用！
management.endpoint.shutdown.enabled=true
management.info.env.enabled=true

