server.port=8080
server.servlet.context-path=

# 日志
logging.level.root=info
logging.file.name=/opt/devops/spring-boot-demo/logs/log.txt
#logging.level.org.springframework=warn


## JDBC 配置
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/spring-boot-demo?useSSL=false&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# 通过配置使用不同的认证方式
# spring.profiles.active=auth-mem


# 启用 Spring Security 配置
# 设置 Spring Security 默认用户名，缺省是 `user`。
#spring.security.user.name=admin
# 设置 Spring Security 默认密码，缺省会打印在控制台。
#spring.security.user.password=admin
#spring.security.user.roles=ADMIN

# 配置 session 过期时间
server.servlet.session.timeout=30m
